# Generated by Django 3.1.2 on 2020-11-13 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursinput',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
